# Generated by Django 3.0 on 2020-01-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200121_1612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlogin',
            table=None,
        ),
    ]
