# Generated by Django 3.0 on 2020-01-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200121_1627'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlogin',
            table='Login',
        ),
    ]
