# Generated by Django 3.0 on 2020-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200121_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='is_usertype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
