# Generated by Django 3.0 on 2020-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userlogin_is_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProject',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('pdes', models.CharField(max_length=100)),
                ('cdetail', models.CharField(max_length=100)),
                ('pdeadline', models.DateField()),
                ('pstartdate', models.DateField()),
                ('pmanagedby', models.CharField(max_length=100)),
                ('pcontract', models.CharField(max_length=100)),
                ('pstatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
    ]
