# Generated by Django 3.0 on 2020-01-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_addproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtask',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('Ttitle', models.CharField(max_length=100)),
                ('Pid', models.IntegerField()),
                ('Tstatus', models.CharField(max_length=100)),
                ('Ttechnology', models.IntegerField(choices=[(1, 'Java'), (2, 'Python'), (3, 'Php'), (4, 'Wordpress'), (5, 'NodeJs')])),
                ('Tassignedto', models.CharField(max_length=100)),
                ('Tassginedby', models.CharField(max_length=100)),
                ('Tassigneddata', models.CharField(max_length=100)),
                ('Tdeadline', models.DateField()),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
