# Generated by Django 3.0 on 2020-01-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_addtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='lastName',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='empid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='login',
        ),
    ]
