# Generated by Django 3.0 on 2020-01-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_addtask_tpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='Tassignedto',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='Tpname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.addProject'),
        ),
    ]
