# Generated by Django 3.0 on 2020-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200129_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='Tassignedto',
            field=models.CharField(max_length=100),
        ),
    ]
